# Generated by Django 5.1.4 on 2024-12-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Guest_number',
            new_name='Guests_number',
        ),
    ]
