# Generated by Django 5.1.4 on 2024-12-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_guest_number_booking_guests_number'),
    ]

    operations = [
    ]
